#%RAML 1.0 NamedExample
  {
    "accountNumber" : 123445678,
    "address" : [
      {
        "typeOfAddress" : "home",
        "city" : "gebze",
        "zip" : 3456
      },
                 
     {
        "typeOfAddress" : "work",
        "city" : "New York",
        "zip" : 7654
      }        
    ]
  }